language: node_js
node_js:
  - 14

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker tag udagram-api-feed pearlicia/udagram-api-feed:v1
  - docker tag udagram-api-user pearlicia/udagram-api-user:v1
  - docker tag udagram-frontend pearlicia/udagram-frontend:v1
  - docker tag udagram-reverseproxy pearlicia/udagram-reverseproxy:v1
  

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - echo "-Pushing images to dockerhub-"
  - docker push pearlicia/udagram-api-feed:v1
  - docker push pearlicia/udagram-api-user:v1
  - docker push pearlicia/udagram-frontend:v1
  - docker push pearlicia/udagram-reverseproxy:v1
  