version: 2.1

jobs:
  lint-app:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "SHA256:egfROIFK6jLx9kDvL5uWa6iaRqW6knAIf+OHMD9tDmI"

  build-docker:
    docker:
      - image: circleci/node:13.8.0  # Use the desired Docker image for your build
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "SHA256:egfROIFK6jLx9kDvL5uWa6iaRqW6knAIf+OHMD9tDmI"
      - run:
          name: Build docker images for each microservices
          command: |
            echo "--------- Installing dependencies -----------"
            # Add your dependency installation steps here if needed
            
            echo "--------- Building Images ------------"
            docker build -t udagram-api-feed ./udagram-api-feed
            docker tag udagram-api-feed pearlicia/udagram-api-feed:v2

            docker build -t udagram-api-user ./udagram-api-user
            docker tag udagram-api-user pearlicia/udagram-api-user:v2
            
            docker build -t udagram-frontend ./udagram-frontend
            docker tag udagram-frontend pearlicia/udagram-frontend:v2

            docker build -t udagram-reverseproxy ./udagram-reverseproxy
            docker tag udagram-reverseproxy pearlicia/udagram-reverseproxy:v2

            echo "-------- All images successfully built ----------"

            echo " ------- login to Docker Hub --------"
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

            echo "-------------- Push all images to Docker Hub -------"
            docker push pearlicia/udagram-api-feed:v2
            docker push pearlicia/udagram-api-user:v2
            docker push pearlicia/udagram-frontend:v2
            docker push pearlicia/udagram-reverseproxy:v2

workflows:
  default:
    jobs:
      - lint-app
      - build-docker:
          requires: [lint-app]
