version: 2.1

jobs:
  linting:
    docker:
      - image: cimg/node:18.0.0
    environment:
      ESLINT_CONFIG: |
        {
          "env": {
            "browser": true,
            "es6": true,
            "node": true
          },
          "extends": [
            "eslint:recommended",
            "plugin:@typescript-eslint/eslint-recommended",
            "plugin:@typescript-eslint/recommended"
          ],
          "globals": {
            "Atomics": "readonly",
            "SharedArrayBuffer": "readonly"
          },
          "parser": "@typescript-eslint/parser",
          "parserOptions": {
            "ecmaVersion": 2018,
            "sourceType": "module"
          },
          "plugins": [
            "@typescript-eslint"
          ],
          "rules": {}
        }
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install eslint @typescript-eslint/parser @typescript-eslint/eslint-plugin

      - run:
          name: Configure ESLint
          command: echo "$ESLINT_CONFIG" > .eslintrc.json

      - run:
          name: Run ESLint
          command: npx eslint .

      - run:
          name: Check linting errors
          command: npx eslint . --quiet

          # command: npx eslint . --quiet || exit 1  # Exit with an error if linting fails

      - add_ssh_keys:
          fingerprints:
            - "SHA256:egfRRqW6knAIf+OHMD9tDmI"

  build-docker:
    machine: true
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "SHA256:egfROIuWa6iaRqW6knAIf+OHMD9tDmI"
      - run:
          name: Build docker images for each microservices
          command: |
            echo "--------- Installing dependencies-----------"
            sudo apt-get update
            sudo curl -LO https://nodejs.org/dist/v18.0.0/node-v18.0.0-linux-x64.tar.xz
            sudo tar -xvf node-v18.0.0-linux-x64.tar.xz
            sudo cp -r node-v18.0.0-linux-x64/{bin,include,lib,share} /usr/
            node --version => v18.0.0
            sudo apt install nodejs

            echo "--------- Building Images ------------"

            docker build -t udagram-api-feed ./udagram-api-feed
            docker tag udagram-api-feed pearlicia/udagram-api-feed:v2

            docker build -t udagram-api-user ./udagram-api-user
            docker tag udagram-api-user pearlicia/udagram-api-user:v2
            
            docker build -t udagram-frontend ./udagram-frontend
            docker tag udagram-frontend pearlicia/udagram-frontend:v2

            docker build -t udagram-reverseproxy ./udagram-reverseproxy
            docker tag udagram-reverseproxy pearlicia/udagram-reverseproxy:v2

            echo "-------- All images successfully built ----------"

            echo " ------- login to dockerhub --------"

            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

            echo "-------------- Push all images to dockerhub -------"

            docker push pearlicia/udagram-api-feed:v2
            docker push pearlicia/udagram-api-user:v2
            docker push pearlicia/udagram-frontend:v2
            docker push pearlicia/udagram-reverseproxy:v2

workflows:
  version: 2
  default:
    jobs:
      - linting
      - build-docker:
          requires: [linting]
